modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="vanillo"
version="${file.jarVersion}"
displayName="Vanillo"
credits="The exaggerated swagger of the Rusty Team"
authors="TheDarkColour, cfrishausen, DJRoundTable, bobertrd"
description='''
Adds a few Vanilla-esque features and tweaks
'''

[[dependencies.vanillo]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.vanillo]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
